package testMovieNight.controllers;

import testMovieNight.OmdbConnection;
import testMovieNight.entities.Movie;
//import testMovieNight.repositories.MovieRepository;
import testMovieNight.repositories.MovieRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.ArrayList;
import java.util.List;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/search") // This means URL's start with /demo (after Application path)
public class MovieController {
    @Autowired // This means to get the bean called movieRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MovieRepository movieRepository;
    private OmdbConnection omdbConnection = new OmdbConnection();

    public MovieController(MovieRepository movieRepository) {
        this.movieRepository = movieRepository;
    }
    public MovieController(){
    }

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody Movie addNewMovie(@RequestParam String id){
        Movie m = movieRepository.findById(id);
        if(m != null){
            return m;
        }
        m = omdbConnection.getMoviesById(id);
        movieRepository.save(m);
        return m;
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Movie> getAllMovies() {
        // This returns a JSON or XML with the users
        return movieRepository.findAll();
    }
    @GetMapping(path="/byTitle")
    public @ResponseBody List<Movie> showMoviesByTitle(@RequestParam String title){
        System.out.println("Halllllååå");
        List<Movie> movieList = new ArrayList<>();
        movieList = omdbConnection.getMoviesByName(title);
        return movieList;
    }

}